### ISSUE TITLE
【bug】新版的字体样式颜色好像没有匹配上默认的颜色

### ISSUE THREAD

**Issue by Tlonglan** [Achuan-2/siyuan-themes-tsundoku-light#12]
新版的字体样式颜色好像没有匹配上默认的颜色
![image](https://user-images.githubusercontent.com/38731172/141645302-cc6d159a-ab95-401c-bf46-4b91475d3c8a.png)

> 默认的字体颜色是红色
![image](https://user-images.githubusercontent.com/38731172/141645270-79762f1d-766e-42b4-9cf5-e6c66f9da823.png)

**Comment by Achuan-2** [comment]
你好，主题介绍部分有提到主题自定义了颜色，所有不会按照官方的颜色来。可以自行复制官方的配色到主题css
主题自定义颜色
![image](https://user-images.githubusercontent.com/60436214/141665718-bf086b2f-bb1d-44c0-a085-f092c96e9bf4.png)

官方颜色
![image](https://user-images.githubusercontent.com/60436214/141665722-7e49ff95-71c0-48bf-94bd-3b8ac3a941cd.png)

**Comment by Tlonglan** [comment]
噢噢原来如此～谢谢～
