### ISSUE TITLE
希望添加界面圆角，看起来更加的圆润一些

### ISSUE THREAD

**Issue by zeng032477** [Achuan-2/siyuan-themes-tsundoku-light#14]

**Comment by Achuan-2** [comment]
可以提供些案例截图吗

**Comment by zeng032477** [comment]
![image](https://user-images.githubusercontent.com/82507525/143974617-560951b0-a062-47a1-bed8-fc10eca6e35c.png)
类似集市内的Rem Craft

**Comment by zeng032477** [comment]
>

**Comment by Achuan-2** [comment]
现在页签和侧栏都加了一点圆角，短时间不会再改了，先关闭谢谢反馈
