### ISSUE TITLE
希望能够添加一些动态元素，例如分割线前面有个动态图标

### ISSUE THREAD

**Issue by wxf-0415** [Achuan-2/siyuan-themes-tsundoku-light#16]
整体真的非常好，非常喜欢。但是感觉确实一些活跃感，希望能添加一些动态的元素。

**Comment by Achuan-2** [comment]
动态元素是说分割线前加小风车之类的嘛

**Comment by wxf-0415** [comment]
是的，是的。。我就采用大佬的主题，和其他主题实现了一丢丢，但是只实现了分割线动画。。希望标题和分割线能有小风车。（当然大佬的主题非常完美了，会持续关注）

**Comment by Achuan-2** [comment]
动态元素还是自己加吧，作为本地笔记，又不是博客，主题是不会加的，还是自己实现吧
ps：主题v1.0.3改了下分割线动画
![image](https://user-images.githubusercontent.com/60436214/146491482-31d076b1-573c-4684-a30a-5b003a0e52f1.png)

**Comment by wxf-0415** [comment]
好的
