### ISSUE TITLE
卡片内的字体颜色修改

### ISSUE THREAD

**Issue by Tlonglan** [Achuan-2/siyuan-themes-tsundoku-light#18]
![image](https://user-images.githubusercontent.com/38731172/147865645-85234379-523d-446a-9fed-27cee1fa11b8.png)

请问这个卡片的标题字体的颜色能修改吗？好像没看到相应的设置

**Comment by Achuan-2** [comment]
不太知道你说的是想要该整个标题块的文字还是部分文字，
改变块的字体颜色：点击块标选【外观】，修改颜色
改变部分字的颜色：选中文字，选择字体
![image](https://user-images.githubusercontent.com/60436214/147929715-7fa50eee-2842-4b68-a482-e2b49b03fcf5.png)

**Comment by Achuan-2** [comment]
先关闭了
