### ISSUE TITLE
折叠嵌入块看不见内容

### ISSUE THREAD

**Issue by Tlonglan** [Achuan-2/siyuan-themes-tsundoku-light#19]
![image](https://user-images.githubusercontent.com/38731172/147865928-8082c862-6f90-4a04-aae8-494e53e9b8bb.png)
折叠的嵌入块什么都看不见，请问这是特性吗？又没有办法显示里面的内容呢？

**Comment by Achuan-2** [comment]
是故意的，对我来说就是折叠就是为了隐藏

**Comment by Tlonglan** [comment]
> 是故意的，对我来说就是折叠就是为了隐藏

噢噢好吧~ 我是觉得折叠只是暂时不想关注详细内容，大标题这样的主要信息还是应该看到的。那我自己魔改你的主题一下吧
谢谢~
