### ISSUE TITLE
三级标题下的间距优化

### ISSUE THREAD

**Issue by aobatu** [Achuan-2/siyuan-themes-tsundoku-light#2]
**问题描述：**
目前三级标题与其下第一行的间距有点小，具体看如下截图：

![image](https://user-images.githubusercontent.com/24941288/126029585-cb2bca17-4946-4f5e-b979-35873fe49b69.png)

**期望优化：**
能否调整下三级标题与第一行的间距，至少保持和其他行的间距宽度一致。

**Comment by aobatu** [comment]
文字上估计间距是一致的，但三级标题由于前面增加了竖行，故从视觉上看，和下面第一行比较挤。

**Comment by Achuan-2** [comment]
谢谢反馈，下一个版本修复
