### ISSUE TITLE
考虑更多个性化属性吗

### ISSUE THREAD

**Issue by banjuer** [Achuan-2/siyuan-themes-tsundoku-light#23]
**非常感谢**提供这么棒的主题, 无论是配色还是整体搭配, 焕然一新, 很现代.
**尤其**使用了**挖空**, **隐藏**(ctrl-e), **table**属性, 没想到还能这么用, 很神奇. 所以**属性**功能应该会有更多玩法. 考虑丰富一下不? 

当然只是个提议, 现在已经够好了

**Comment by Achuan-2** [comment]
hh，谢谢喜欢。
属性这种东西其实是很个人的东西，而且不同主题不好迁移。
如果有好的提议可以建议，我暂时没有想到好的idea
重要的还是好好记录自己的想法，我最近看到obsidian的相关视频，发现大都在谈论插件、把obsidian改造成notion，已经完全走偏了，我觉得很可怕，对我来说，我得警惕自己掉入这个坑。
主题之所以做的比较简洁，没加入太多元素，也是希望自己专注于内容，专注思考提升能力才是正道
