### ISSUE TITLE
#建议优化#新建文档按钮鼠标悬停时的阴影衬底不对称

### ISSUE THREAD

**Issue by Faith-YSQ** [Achuan-2/siyuan-themes-tsundoku-light#25]
<img width="260" alt="Snipaste_2022-03-22_11-57-00" src="https://user-images.githubusercontent.com/66512309/159405198-bea253f2-a679-4a5b-99da-7f56cd584b4d.png">

**Comment by Achuan-2** [comment]
感谢反馈，已修复
