### ISSUE TITLE
背景颜色太白

### ISSUE THREAD

**Issue by 5kyfkr** [Achuan-2/siyuan-themes-tsundoku-light#28]
新版本背景颜色比旧版提亮太多，感觉已经是纯白了，希望改回旧版颜色
![image](https://user-images.githubusercontent.com/63196026/161173686-82320b5a-2585-403e-ade2-d6cf5aae45b5.png)

**Comment by Achuan-2** [comment]
我是故意的，因为light主题就是为了打印服务的，之前的背景色会导致打印效果和思源显示效果有比较差别。
为了护眼可以尝试切换stone、green主题

**Comment by 5kyfkr** [comment]
好滴，那没事了，还以为是BUG
