### ISSUE TITLE
还是标签页问题，强迫症

### ISSUE THREAD

**Issue by HoGafi** [Achuan-2/siyuan-themes-tsundoku-light#29]
![image](https://user-images.githubusercontent.com/32252229/161261529-b0c83646-a651-4e1f-9fd5-c6b18a3562ed.png)
如图，红箭头这里有点杂色

**Comment by HoGafi** [comment]
![image](https://user-images.githubusercontent.com/32252229/161261647-7ffed92c-0c21-424d-9248-9c8511678690.png)

**Comment by Achuan-2** [comment]
见https://github.com/Achuan-2/siyuan-themes-tsundoku-light/issues/27
有空再修复

**Comment by Achuan-2** [comment]
已修复80c20f2cb8bb77ca82c30e944e370eb890317097
