### ISSUE TITLE
“标记”的文字为什么会被隐去呀？

### ISSUE THREAD

**Issue by Duarsafin** [Achuan-2/siyuan-themes-tsundoku-light#31]
思源的“标记”大概是对应着Obsidian的“高亮”，如果高亮的内容被隐藏了，无法一目了然，需要鼠标移动到上面去才显示，我个人使用时感觉是挺困难的（虽然系统版的标记也并不显眼就是了）。不知道是不是我对这个功能的理解不到位，希望作者大大帮忙解惑。

**Comment by Achuan-2** [comment]
主题的高亮隐去是为了复习记忆的

**Comment by Achuan-2** [comment]
如果要给文字加背景色，可以选择背景色
![image](https://user-images.githubusercontent.com/60436214/162173737-9ad75b44-8d56-48cd-bd4b-9b9d2c95f2a6.png)

**Comment by Achuan-2** [comment]
emm，我思考下，可能要把标记文字隐去给砍了

**Comment by Duarsafin** [comment]
原来是这样，明白了

**Comment by Duarsafin** [comment]
感谢作者大大解惑
