### ISSUE TITLE
代码块行号显示问题

### ISSUE THREAD

**Issue by coderlemon17** [Achuan-2/siyuan-themes-tsundoku-light#32]
![image](https://user-images.githubusercontent.com/39124095/163512089-882e1777-aee1-4bc8-8aa3-a2ac4e8a4f3d.png)
- 如图, 当代码行数达到三位数的时候, 行号的显示出现了问题.
   - 例如 `100`, 被显示成了`10\n0`

**Comment by Achuan-2** [comment]
是最新的主题吗

**Comment by coderlemon17** [comment]
我刚刚更新了一下, 然后重启了思源, 但是行号显示还是有问题.
![image](https://user-images.githubusercontent.com/39124095/163513144-8d12e93b-a03f-4317-85c0-7468fed21efe.png)
![image](https://user-images.githubusercontent.com/39124095/163513190-438007f5-9857-4e14-aa47-259ed54f4af7.png)

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/163513340-8ba52f6d-2134-4349-9bc9-08e467bd5c08.png)
我没有问题的哦，编辑器字体和大小设置？

**Comment by coderlemon17** [comment]
字体是Times New Roman, 大小是`24`.

**Comment by Achuan-2** [comment]
字体调大了，确实有点问题，我自己平常都用18号字体

**Comment by coderlemon17** [comment]
感谢, 实测调成`23`就可以了~

**Comment by Achuan-2** [comment]
没事，有空我再修一修

**Comment by Achuan-2** [comment]
主题现在的行号设置已经是跟随官方了
我用官方主题如果字号调大也有这个问题，
![image](https://user-images.githubusercontent.com/60436214/163758274-dad3d7e0-8f7b-45e4-82ce-af4e9302afdf.png)

**Comment by coderlemon17** [comment]
更新了一下主题之后代码块行号似乎不会对齐了:
![image](https://user-images.githubusercontent.com/39124095/166202310-2243fa5e-67f9-46cb-8924-67faf5ed41cd.png)
检查了一下官方默认主题是可以对齐的:
![image](https://user-images.githubusercontent.com/39124095/166202387-a15fa74a-8bc5-4e07-8812-baa660361e56.png)

**Comment by coderlemon17** [comment]
谢谢, 测试已正常.
