### ISSUE TITLE
主题建议

### ISSUE THREAD

**Issue by yulutongfei** [Achuan-2/siyuan-themes-tsundoku-light#34]
大佬为啥你这个主题里面的icon图标都是自己挨个在src文件夹里面添加的。
我上次为了加一个leetcode的图标。特定去改了那个icon的css文件，感觉挨个去加有点麻烦。

能不能统一从 https://xxx/favicon.ico里面获取图标。
大部分网站的图标都是这个地址

**Comment by Achuan-2** [comment]
这样得用js哦，暂时没时间研究能不能实现
有一个quicker动作可以快速获取图标并保存到文件夹，我现在添加图标都是用这个动作
