### ISSUE TITLE
标签页被顶住时无法随着顶栏宽度变化自动调整宽度

### ISSUE THREAD

**Issue by litcu** [Achuan-2/siyuan-themes-tsundoku-light#35]
采用两分栏，右侧两个标签页被钉住时，无法随着调整分栏的宽度自动调整被钉住的页签宽度。

![t_bug](https://user-images.githubusercontent.com/53759402/165200895-863bf7fa-2012-40e6-bfff-4db89c225c90.gif)

**Comment by Achuan-2** [comment]
谢谢反馈，下个版本取消钉住页签的宽度设置，改成默认主题的样式

发件人: ***@***.***>
发送时间: 2022年4月26日 9:30
收件人: ***@***.***>
抄送: ***@***.***>
主题: [Achuan-2/siyuan-themes-tsundoku-light] 标签页被顶住时无法随着顶栏宽度变化自动调整宽度 (Issue #35)


采用两分栏，右侧两个标签页被钉住时，无法随着调整分栏的宽度自动调整被钉住的页签宽度。

[t_bug]<https://user-images.githubusercontent.com/53759402/165200895-863bf7fa-2012-40e6-bfff-4db89c225c90.gif>

―
