### ISSUE TITLE
部分报错，如图所示。

### ISSUE THREAD

**Issue by william2113** [Achuan-2/siyuan-themes-tsundoku-light#36]
<img width="1742" alt="截屏2022-05-04 20 37 58" src="https://user-images.githubusercontent.com/65440664/166682653-3b7803f7-1a5f-43d8-ba4f-ac7550d1f1c0.png">
思源笔记版本2.0.2，MAc客户端

**Comment by Achuan-2** [comment]
doc arr css的问题已修复，js的我这里没问题，也不会js就暂时算了
