### ISSUE TITLE
文档树 图标和文字没对齐

### ISSUE THREAD

**Issue by lsb226** [Achuan-2/siyuan-themes-tsundoku-light#37]
希望作者改下
![image](https://user-images.githubusercontent.com/16093704/173768186-6ce37ba1-cc1f-4dbf-8a88-e2a6e0c3aea9.png)

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/176088982-e0da16c9-5b9a-4d52-b64a-5aff01a03674.png)
已修复

**Comment by lsb226** [comment]
![image](https://user-images.githubusercontent.com/16093704/176089580-3f0ee469-2bc3-4ed3-82bf-cfc69d133bcc.png)
还是没变

**Comment by Achuan-2** [comment]
取消了之前自定义的emoji高度
https://github.com/Achuan-2/siyuan-themes-tsundoku-light/commit/3ab9f4c95db229bee136b74ac3a92d864b3b769b

**Comment by lsb226** [comment]
我去theme.js 里面去掉 line-height: 28px;
    height: 28px; 就好了 是不是改完 没更新呢

**Comment by lsb226** [comment]
版本是 1.3.3

**Comment by lsb226** [comment]
集市 里的 1.3.3 还有这个在
![image](https://user-images.githubusercontent.com/16093704/176092255-37065d98-7515-44c6-8f66-c1b36e17906d.png)

**Comment by Achuan-2** [comment]
1.3.4才去掉了

**Comment by lsb226** [comment]
好的 明白了
