### ISSUE TITLE
挖空的特性不能遮挡下划线

### ISSUE THREAD

**Issue by jueshikuangshen** [Achuan-2/siyuan-themes-tsundoku-light#4]
![image](https://user-images.githubusercontent.com/47046461/130751993-af321edc-a472-420d-a9bb-57a1d568278d.png)
感谢大佬精美的主题，请问怎么让下划线也被遮住？

**Comment by Achuan-2** [comment]
已修复
https://github.com/Achuan-2/siyuan-themes-tsundoku-light/commit/6bedbe2e1271b0995d83a618e75314b6092cbb83
