### ISSUE TITLE
任务栏失焦时会显示为默认主题

### ISSUE THREAD

**Issue by coderlemon17** [Achuan-2/siyuan-themes-tsundoku-light#40]
# 版本:
Siyuan 2.4.3
Tsundoku-light: v1.4.2

# 问题描述
> 任务栏指的是:
> ![image](https://user-images.githubusercontent.com/39124095/197094321-35ae4c28-02ef-4ba9-9d84-2ace36070e14.png)

1. 使用Tsundoku-light主题, 当窗口失焦时, 任务栏会变成黑色.

**正常任务栏颜色**
![image](https://user-images.githubusercontent.com/39124095/197094176-70544dca-e0aa-4cc5-b382-c7199f5cbdbc.png)

**失焦后任务栏颜色**
![image](https://user-images.githubusercontent.com/39124095/197093961-9a27b133-e04e-401e-b56b-9706233614b3.png)

2. 切换回默认主题后没有此问题, 怀疑是失焦后, 任务栏变为了默认主题配色.
![image](https://user-images.githubusercontent.com/39124095/197093880-56b941f0-70f9-453c-88db-05b2d1911090.png)

**Comment by Achuan-2** [comment]
感谢反馈，已修复
