### ISSUE TITLE
优化标题样式

### ISSUE THREAD

**Issue by linglongyoudoufu** [Achuan-2/siyuan-themes-tsundoku-light#42]
我很难区分加粗和第六级标题的区别 或者是相邻级别的标题的区别.希望能优化标题样式加以区分

**Comment by Achuan-2** [comment]
补充
![image](https://user-images.githubusercontent.com/60436214/206499694-235cd20d-4d9d-48aa-8c1d-65854b81a895.png)

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/206830670-b0772342-3106-472d-971a-4e29a239a3b1.png)
![image](https://user-images.githubusercontent.com/60436214/206835382-018158cf-265c-45a7-bf51-85f3f2d1af50.png)

![image](https://user-images.githubusercontent.com/60436214/206835038-6c6b1b80-51c0-4427-b206-050259171e45.png)
