### ISSUE TITLE
blueprint 的三级往后的标题难区分

### ISSUE THREAD

**Issue by Kitsuta-le** [Achuan-2/siyuan-themes-tsundoku-light#5]
![image](https://user-images.githubusercontent.com/88605687/132990140-5b3f197d-2c8e-405b-af65-37aac9993304.png)
今天刚用上就惊艳到，大佬的审美真的太棒了！大老爷们儿也要给你疯狂打call！

**Comment by Achuan-2** [comment]
啊，你好，谢谢肯定。
但这个主题-blueprint不是我制作的

**Comment by Kitsuta-le** [comment]
> 啊，你好，谢谢肯定。
> 但这个主题-blueprint不是我制作的
> 请去这里反馈https://github.com/YYHCOPPOLO/BluePrint-From-Tsundoku

我靠，我看风格差不多，名字也有你。。。 这下老尴尬了。。。。。
尴尬归尴尬 call照样打 老哥牛逼！

**Comment by Achuan-2** [comment]
> > 啊，你好，谢谢肯定。
> > 但这个主题-blueprint不是我制作的
> > 请去这里反馈https://github.com/YYHCOPPOLO/BluePrint-From-Tsundoku
> 
> 我靠，我看风格差不多，名字也有你。。。 这下老尴尬了。。。。。
> 尴尬归尴尬 call照样打 老哥牛逼！

因为那个主题是根据Tsundoku Light改的

**Comment by Kitsuta-le** [comment]
> > > 啊，你好，谢谢肯定。
> > > 但这个主题-blueprint不是我制作的
> > > 请去这里反馈https://github.com/YYHCOPPOLO/BluePrint-From-Tsundoku
> > 
> > 
> > 我靠，我看风格差不多，名字也有你。。。 这下老尴尬了。。。。。
> > 尴尬归尴尬 call照样打 老哥牛逼！
> 
> 因为那个主题是根据Tsundoku Light改的

啊啊难怪hhh
