### ISSUE TITLE
块菜单增强

### ISSUE THREAD

**Issue by Achuan-2** [Achuan-2/siyuan-themes-tsundoku-light#55]
添加用monaco编辑器打开、在新窗口打开
![image](https://user-images.githubusercontent.com/60436214/208144828-0b60634d-a320-4255-af4b-d090693ef44d.png)

**Comment by yef-dev** [comment]
似乎块增强随着思源更新无法使用了，sad o(TヘTo)

**Comment by Achuan-2** [comment]
主题和思源都是最新版吗，我这里测试没问题

**Comment by yef-dev** [comment]
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/113995449/1c3b3dd2-6f5d-4cde-a52f-257b3e9f3d04)
思源版本v2.8.7，主题是今天才下载的（因为主题换了一个名字上架，所以卸载了原来的）
但是没有“更多”选项欸（如图）；使用鼠标中键+alt也没有反应（虽然鼠标中键真的很难按😂）

**Comment by Achuan-2** [comment]
我这边是正常的
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/60436214/a73be0d1-bc42-427d-bb62-ae75a880ecab)
确定下主题版本是不是v1.7.0
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/60436214/ec17f3e7-604a-4549-80fe-74a55544a633)

**Comment by Achuan-2** [comment]
哦哦，是有点问题，思源改了集市下载的机制，显示是仓库名，导致无法导入了
![image](https://github.com/Achuan-2/siyuan-themes-tsundoku/assets/60436214/49684a3c-f9de-491a-b04e-bd0de5a84eb1)

**Comment by Achuan-2** [comment]
已经更新了，其实可以直接打开主题文件夹，siyuan-themes-tsundoku重命名为Tsundoku，应该就可以解决了

**Comment by yef-dev** [comment]
太感谢啦！！ヾ(•ω•`)o
