### ISSUE TITLE
侧边栏状态bug

### ISSUE THREAD

**Issue by fanglypro** [Achuan-2/siyuan-themes-tsundoku-light#6]
侧边栏有两种状态，一种是聚焦状态，一种是未聚焦状态，本主题没有区分这两个状态，可以看这个：https://ld246.com/article/1631270943064

![image](https://user-images.githubusercontent.com/57083732/133598628-f2fb9b67-4e07-4e19-a797-ecc1b6d326d4.png)

![image](https://user-images.githubusercontent.com/57083732/133598649-002e25f7-c4bb-429e-a85b-7d15e09ab95e.png)

**Comment by Achuan-2** [comment]
感谢反馈，下一个版本修复https://github.com/Achuan-2/siyuan-themes-tsundoku-light/commit/74b196da312a76843b20236002861f06188d2160
