### ISSUE TITLE
bug when collapsing quote blocks

### ISSUE THREAD

**Issue by eslam-gomaa** [Achuan-2/siyuan-themes-tsundoku-light#7]
There is a bug when collapsing `quote blocks`

![image](https://user-images.githubusercontent.com/33789516/139103441-523e5e94-a2e3-4eff-88e2-839687d264bf.png)

![image](https://user-images.githubusercontent.com/33789516/139103411-23a496e8-8d16-4fb7-9738-ee00be06a7c6.png)

---

![image](https://user-images.githubusercontent.com/33789516/139103681-fc3717db-6ab7-4dce-a548-f325af0ca424.png)

![image](https://user-images.githubusercontent.com/33789516/139103707-ca9a4145-122e-4a8c-ab4d-6fbdc356292c.png)

**Comment by Achuan-2** [comment]
Thanks，I have fixed
