### ISSUE TITLE
行内代码块有Bug

### ISSUE THREAD

**Issue by skyls03** [Achuan-2/siyuan-themes-tsundoku-light#8]
行内代码块部分 删除不彻底。在表格中，会导致该单元格无法编辑
默认主题，不会有此问题
具体看图：
![bug](https://user-images.githubusercontent.com/45219522/140317771-e8694b8b-9604-46c1-8264-69c073a8ad14.gif)

另外两个主题（Tsundoku-dark和Tsundoku-Texture）也有这样的问题

**Comment by Achuan-2** [comment]
谢谢，已修复
